include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    avoid_void_async: true
    
    avoid_print: true
    use_build_context_synchronously: true
    avoid_empty_else: true
